### ISSUE TITLE
copy-paste style also copies SRID

### ISSUE THREAD

**Issue by jramanue** [openjump-gis/openjump#145]
You have two projects, A and B. Data sources are a mix of shapefiles, geojson files, and PostGIS queries. For some of the PostGIS queries, tables/views can change frequently and it's important that they remain in the database rather than being saved as e.g. geojson. The two projects are visually just about the same, but B is a reprojection of A and uses a different SRID.

As you are completing the reprojection in project B, you create a layer which is a query to a PostGIS view which is identical to the corresponding view in project A except for using a differen6t SRID. (E.g. geometry column is reproduced from the same PostGIS expression except for a changed SRID.) But you want the layer in project B to look just like the layer in Project A. So you create the layer using the correct parameters for a Data Store Layer. Everything is fine but the appearance. In particular, the SRID in project B is *correctly* brought in from PostGIS.

So you go to project A and do Style > Copy. Then you go back to project B and do Style > Paste. Everything looks fine. But OpenJump now says the data source for the layer has to be saved, and if you do Layer > Set SRID, the SRID is the same as the layer in project A that you just copied -- and therefore wrong. Of course you can manually change the SRID for the layer in Project B. But now it's not a Data Store Layer any more, and when the data changes in the database, OpenJump won't see the change.

The only workaround I have found is to paste the Style in project B, change the SRID manually, then create a Data Store query Layer *again*, paste the style from the first created layer in project B into the new layer, and now OpenJump will leave the new layer as a Data Store Layer and the SRID will be correct. This is a real nuisance.

Maybe copying the SRID is intended behavior for a Style copy, but it sure takes me by surprise!

**Comment by mukoki** [comment]
Thank you for your report. I can see two problems in your use case : 
- srid style should probably be excluded from the copy/paste style plugin as there is no reason that a user wants to copy styles and srid together
- I wonder why setting a new srid detaches the source from the layer. In OpenJUMP, setting a srid does not transform coordinates, it just set a tag on the dataset. So I can see no reason to loose the datasource.
 
Let me some time to investigate both points.

**Comment by mukoki** [comment]
The first point should be fixed in r5312 (paste style does not paste the srid anymore). Please, test if it solves the problem.
For the second point, sorry, I could not reproduce the problem. Perhaps I misunderstood how exactly you loaded and changed the srid of the datastore layer in project B. In my test, when I set a new SRID in a datastore layer, I don't loose the datasource.

**Comment by chrisdebian** [comment]
The SRID-exclusion fix mukoki mentions (r5312) is confirmed present in current `main` — `PasteStylesPlugIn.java` explicitly skips `SRIDStyle` when pasting:

```java
// We don't want to copy SRID style with other styles as it is something rather different
if (style instanceof SRIDStyle) continue;
```

I wasn't able to test this against a live build (no Maven/display available in my environment), so I can only confirm the fix is in the source, not that it resolves the original report from the UI side. mukoki's second question above (why setting a new SRID detaches the datastore source) also remains open and I have no way to check that statically.

**Comment by edeso** [comment]
@chrisdebian kindly try the snapshot builds available at https://sourceforge.net/projects/jump-pilot/files/OpenJUMP2_snapshots/

**Comment by chrisdebian** [comment]
Thanks for the pointer — I now have Maven installed and the project builds cleanly (all 147 tests pass), so I don't need a prebuilt snapshot for that part. I still don't have a display available in this environment though, so I can't click through the Swing UI to test interactively. Happy to have someone confirm the UI behaviour directly if that's more useful than a source-level check.
